package:
  name: sweep2png
  version: 0.1.0

source:
  path: ../

requirements:
  build:
    - libpng # [unix]
    - zlib # [unix]
    - libpng-gcc # [win]
    - zlib-gcc # [win]
    - mingw #[win]
  run:
    - libpng # [unix]
    - zlib # [unix]

test:
  files:
    - map
    - Si_5grains_mesh.log
  commands:
    - sweep2png Si_5grains_mesh.log map/Si_70 0.7 cubic

about:
  license: GPL
  home: https://github.com/praxes/sweep2png
  summary: High energy diffraction microscopy scripts
