package:
  name: sweep2png
  version: master

source:
  path: ../

build:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libpng
    - zlib
  run:
    - libpng
    - zlib

test:
  files:
    - map
    - Si_5grains_mesh.log
  commands:
    - sweep2png Si_5grains_mesh.log map/Si_70 0.7 cubic

about:
  license: LGPL
  home: https://github.com/praxes/sweep2png
  summary: High energy diffraction microscopy scripts
